name = "OpenQuantumSystems"
uuid = "12345678-1234-5678-9abc-123456789abc"
version = "0.1.0"
authors = ["Albert Trullols <albert@example.com>"]

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"

[compat]
julia = "1.10"
QuantumOptics = "1.2"
Plots = "1.41"
